################################
# Misc configuration
################################
spring.cloud.config.server.git.uri=file:///D:/Microservice_Workspace/web-config
spring.cloud.config.server.git.username=${gitUname}
spring.cloud.config.server.git.password=${gitUpwd}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.basedir=${app.runtime.base}/git/checkout
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.refreshRate=30
app.runtime.base=/data/ForrREST/configservice
################################
# logging configuration
################################
logging.file=${app.runtime.base}/logs/configservice.log
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.actuate=WARN
logging.level.org.springframework.boot.autoconfigure.security=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=DEBUG
logging.path=/logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.=error
################################
# server configuration	
################################
server.context-path=/ForrREST
server.port=9000
server.tomcat.basedir=${app.runtime.base}/tomcat
server.tomcat.accesslog.enabled=true
################################
# management configuration
################################
management.port=9990
management.context-path=/manage
management.security.enabled=true
management.security.roles=ADMIN
security.basic.enabled=true
security.user.name=${configUser}
security.user.password=${configPass}
endpoints.health.sensitive=false
endpoints.shutdown.enabled=true
endpoints.shutdown.sensitive=false
